### ISSUE TITLE
android清单文件配置地图key后应用启动闪退问题

### ISSUE THREAD

**Issue by shiqiangdva** [1035901787/react-native-s-baidumap#2]
`
        <meta-data
            android:name="com.baidu.lbsapi.API_KEY"
            android:value="百度地图申请的key值" >
        </meta-data>`
android清单文件添加配置后,应用启动闪退报错: 
`Process: com.lgtrade.glw.prod, PID: 17497
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
        at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:339)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:775)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:187)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:155)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:123)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:111)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:189)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:154)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:429)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:38)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1049)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1008)
        at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:124)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:969)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.lgtrade.glw.prod-46AlgfCjrr5yAPhc3IH2Vg==/base.apk"],nativeLibraryDirectories=[/data/app/com.lgtrade.glw.prod-46AlgfCjrr5yAPhc3IH2Vg==/lib/arm64, /data/app/com.lgtrade.glw.prod-46AlgfCjrr5yAPhc3IH2Vg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:339) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:775) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:187) 
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:155) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:123) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:111) 
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:189) 
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:154) 
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:429) 
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:38) 
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1049) 
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1008) 
        at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:124) 
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:969) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:214) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232) 
        at java.lang.Thread.run(Thread.java:764) `

安卓配置文档书在0.60.0+版本只需要添加这一项配置(我的版本是0.60.6), 是否还需要额外配置, 如权限等?

**Comment by 1035901787** [comment]
没看出问题所在，麻烦提供一下js代码和android配置的代码截图

**Comment by shiqiangdva** [comment]
![11](https://user-images.githubusercontent.com/24239375/75751020-73d7fd80-5d60-11ea-9bce-90f5fce7e995.png)

**Comment by shiqiangdva** [comment]
![22](https://user-images.githubusercontent.com/24239375/75751055-87836400-5d60-11ea-9c5b-003cb06ace40.png)

**Comment by shiqiangdva** [comment]
11是android应用启动报错异常信息
22是android清单文件配置代码
不知道方不方便加个VX(sq1114005726)具体沟通一下?

**Comment by 1035901787** [comment]
是否使用了其它第三方组件swiper，我看错误信息中提示的是这个

**Comment by shiqiangdva** [comment]
确实有使用 react-native-swiper, 一个轮播图的依赖库, 请问Android配置0.60.0+ 是否还需要在手动使用react-native link命令执行一次? 是否还需要在MainApplication.java文件添加packages.add(new BaiduMapPackage());或是其它配置呢?

**Comment by 1035901787** [comment]
不需要手动link，也不需要配置MainApplication.java，配置好key后直接运行

**Comment by shiqiangdva** [comment]
是 我也是这样做的... IOS正常 Android不清楚问题的原因 应用启动后再欢迎页闪退崩溃  正在排查问题

**Comment by shiqiangdva** [comment]
implementation 'androidx.appcompat:appcompat:1.2.0-alpha02'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha03'
解决了... 过程很坎坷... 最后解决方式是翻墙在gradle配置里面下载上面的两个包就好了, 是使用了react-navigation和react-native-screens所引发的问题.
